### ISSUE TITLE
build fails: JavaExtendedContextWithMavenAndSourceCodeTest.testContextFromCustomMavenProject

### ISSUE THREAD

**Issue by hohwille** [m-m-m/code#41]
Build is currently broken (after merging #38 ?):
```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.916 s <<< FAILURE! - in net.sf.mmm.code.impl.java.JavaExtendedContextWithMavenAndSourceCodeTest
[ERROR] testContextFromCustomMavenProject  Time elapsed: 1.019 s  <<< ERROR!
net.sf.mmm.util.exception.api.ObjectNotFoundException:
Could NOT find object "net.sf.mmm.code.api.type.CodeType" for "com.maven.project.sampledatamanagement.dataaccess.api.SampleDataEntity"!
1e721e90-9b73-4de2-848e-5c76588b497b:NotFound
        at net.sf.mmm.code.impl.java.JavaExtendedContextWithMavenAndSourceCodeTest.testContextFromCustomMavenProject(JavaExtendedContextWithMavenAndSourceCodeTest.java:114)
```

**Comment by hohwille** [comment]
Actual cause why `SampleDataEntity` could not be found:
```
java.lang.NoClassDefFoundError: com/devonfw/module/basic/common/api/entity/GenericEntity
```

So still the dependency resolution is incorrect and therefore classload incomplete...

**Comment by hohwille** [comment]
Activated logging and got messages like this:
```
01:38:50.003 [main] DEBUG n.s.m.c.i.j.s.m.MavenDependencyCollector - Omitting dependency due to missing file D:\projects\mmm\workspaces\main\code\java\impl\src\test\resources\testdata\localmavenproject\maven.project\target\eclipse-target\classes for source null
```

So why is the path containing `target\eclipse-target`? This does not seem to make any sense...

**Comment by hohwille** [comment]
After running `mvn install` manually in `code\java\impl\target\test-classes\testdata\localmavenproject\maven.project` it downloaded the dependencies and the test turned green.
Why did this not happen during `mvn clean install` of entire mmm-code? It should actually trigger maven build and that was also logged earlier.

**Comment by hohwille** [comment]
solved GPG but now getting
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.408 s <<< FAILURE! - in net.sf.mmm.code.java.maven.impl.MavenBridgeImplTest
[ERROR] testReadProject  Time elapsed: 0.328 s  <<< ERROR!
java.lang.IllegalStateException: Failed to read effective model for pom.xml. Try to run 'mvn help:effective-pom' in that folder manually. If that fails, fix your pom.xml. Otherwise report a bug at https://github.com/m-m-m/code/issues/new/choose
	at net.sf.mmm.code.java.maven.impl.MavenBridgeImplTest.testReadProject(MavenBridgeImplTest.java:84)
Caused by: org.apache.maven.model.building.ModelBuildingException:
3 problems were encountered while building the effective model for net.sf.m-m-m:mmm-code-java-maven:1.0.0
[FATAL] Non-readable POM /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom: /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom (No such file or directory) @ /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-util-io:jar is missing. @
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-util-test:jar is missing. @

	at net.sf.mmm.code.java.maven.impl.MavenBridgeImplTest.testReadProject(MavenBridgeImplTest.java:84)

[INFO] Running net.sf.mmm.code.java.maven.impl.MavenLocalRepositoryLocatorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in net.sf.mmm.code.java.maven.impl.MavenLocalRepositoryLocatorTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MavenBridgeImplTest.testReadProject:84 » IllegalState Failed to read effective...
[INFO]
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by hohwille** [comment]
```
java.lang.IllegalStateException: Failed to read effective model for /Users/hohwille/projects/mmm/workspaces/main/code/java/impl/pom.xml. Try to run 'mvn help:effective-pom' in that folder manually. If that fails, fix your pom.xml. Otherwise report a bug at https://github.com/m-m-m/code/issues/new/choose
	at net.sf.mmm.code.java.maven.impl.MavenBridgeImpl.readEffectiveModel(MavenBridgeImpl.java:188)
	at net.sf.mmm.code.java.maven.impl.MavenBridgeImpl.readEffectiveModelFromLocation(MavenBridgeImpl.java:202)
	at net.sf.mmm.code.impl.java.source.maven.JavaSourceProviderUsingMaven.createFromLocalMavenProject(JavaSourceProviderUsingMaven.java:173)
	at net.sf.mmm.code.impl.java.source.maven.JavaSourceProviderUsingMaven.createFromLocalMavenProject(JavaSourceProviderUsingMaven.java:236)
	at net.sf.mmm.code.impl.java.source.maven.JavaSourceProviderUsingMaven.createFromLocalMavenProject(JavaSourceProviderUsingMaven.java:220)
	at net.sf.mmm.code.impl.java.source.maven.JavaSourceProviderUsingMaven.createFromLocalMavenProject(JavaSourceProviderUsingMaven.java:196)
	at net.sf.mmm.code.impl.java.JavaExtendedContextWithMavenAndSourceCodeTest.getContext(JavaExtendedContextWithMavenAndSourceCodeTest.java:45)
	at net.sf.mmm.code.impl.java.JavaExtendedContextWithMavenAndSourceCodeTest.testTypeWithSourceFromFilesystem(JavaExtendedContextWithMavenAndSourceCodeTest.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.apache.maven.model.building.ModelBuildingException: 7 problems were encountered while building the effective model for net.sf.m-m-m:mmm-code-java-impl:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ net.sf.m-m-m:mmm-code-java-impl:${revision}, /Users/hohwille/projects/mmm/workspaces/main/code/java/impl/pom.xml
[FATAL] Non-readable POM /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom: /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom (No such file or directory) @ /Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-code-bom/1.0.0/mmm-code-bom-1.0.0.pom
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-code-base:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-code-java-parser:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-code-java-maven:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for net.sf.m-m-m:mmm-util-test:jar is missing. @ 

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:490)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:432)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:422)
	at net.sf.mmm.code.java.maven.impl.MavenBridgeImpl.readEffectiveModel(MavenBridgeImpl.java:185)
	... 74 more
```

So why is mmm-code parsed if test project `localmavenproject/maven.project` is read?

**Comment by hohwille** [comment]
`mmm-code-bom-1.0.0.pom` - where does `1.0.0` come from? There are only beta versions, yet...

**Comment by hohwille** [comment]
Indeed I was correct with my review thoughts of #40 
The behaviour of the fix is incorrect and different to what maven does:
The paremt `pom.xml` of `mmm-code` on my disc is the mmm root pom that has version 1.0.0.
As with the changes of #40 introduced with #38 do not read `.mvn/maven.config` in case there is a `../pom.xml` file this error occurs.

**Comment by hohwille** [comment]
Finally fixed and release staged to maven central.
